//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::car_registration::Entity as CarRegistration;
pub use super::maintenance_history::Entity as MaintenanceHistory;
pub use super::vehicle_notes::Entity as VehicleNotes;
