//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "vehicle_notes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub car_id: i32,
    pub body: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::car_registration::Entity",
        from = "Column::CarId",
        to = "super::car_registration::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CarRegistration,
}

impl Related<super::car_registration::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CarRegistration.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
