[package]
name = "card_reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6.2"
hex = "0.4.3"
iso7816-tlv = "0.4.3"
once_cell = "1.17.1"
pcsc = "2.8.0"
thiserror = "1.0.40"
